### ISSUE TITLE
TALK: Task como task runner

### ISSUE THREAD

**Issue by larsx2** [devzcommunity/community#46]
## Acerca

[Task](https://taskfile.dev/) es una herramienta de automatización de tareas repetitivas configurable a través de archivos YAML.

## Beneficios

La audiencia aprenderá como configurar _Task_ para automatizar comandos básicos de shell así como aprovechar las funcionalidades avanzadas de la herramienta como interactividad, variables de entorno, parámetros, pruebas de idempotencia y precondiciones.

## Preview

```yaml
version: '3'

env:
  DATABASE_PASSWORD: "my-secure-password"

tasks:
  up:
    desc: Set up dev environment
    cmds:
      - docker-compose up -d
      - sleep 2
      - task: db:migrate-up
      - echo "dev environment is ready."

  down:
    desc: Tear down dev environment
    cmds:
      - docker-compose down -v

  reset:
   desc: Rest dev environment
    cmds:
      - task: down
      - task: up

  db:connect:
    desc: Connect to localhost database
    internal: true
    cmds:
      - PGPASSWORD=$DATABASE_PASSWORD psql -h localhost -d mydb -U user {{.OPTIONS}}
    preconditions:
      - sh: which psql
      - msg: "psql command not found, please install and run again"
      
  db:migrate-up:
    cmds:
      - task: db:connect
        vars: { OPTIONS: '-f migrations/base.up.sql' }

  db:migrate-down:
    cmds:
      - task: db:connect
        vars: { OPTIONS: '-f migrations/base.down.sql' }
```

## Referencias
- https://taskfile.dev/
- https://taskfile.dev/usage/
- https://taskfile.dev/styleguide/
